### Multidimensional Arrays ans Tensors 


In [17]:
#numpy.array/numpy.ndarray = data structure representation of a tensor 
#pytorch.tensor/pytorch.Tensor = data structure representation of a tensor 

import numpy as np 
import torch

a = np.array([1. , 2. ,3.])
a.shape
b = torch.tensor([1. , 2.,3.]) 


#dot product with 
print(a.dot(a))
print(b.matmul(b))

#To get the type
b.numpy()


14.0
tensor(14.)


array([1., 2., 3.], dtype=float32)

In [18]:
#
torch.tensor(a)

tensor([1., 2., 3.], dtype=torch.float64)

In [20]:
##Specify the type upon construction 

c = torch.tensor([1.,2.,3.] , dtype = torch.float)
d = torch.tensor([1 ,2,3])
print(c,d)

tensor([1., 2., 3.]) tensor([1, 2, 3])


In [22]:
##Changing types on the fly 
c = torch.tensor([1. , 2. , 3.])
d = torch.tensor([1,2,3])

print(c.float() - d.float())
print(c.double() - d.double())
print(c.int() - d.int())
print(c.long() - d.long())


tensor([0., 0., 0.])
tensor([0., 0., 0.], dtype=torch.float64)
tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0])


### Loading data into GPU 

In [26]:
##After installing CUDA

#print(torch.cuda.is_available())
#b = b.to(torch.device('cuda:0'))
#b = b.to(torch.device('cpu'))

### Vectors in PyTorch

In [28]:
#elementwise multiplication 
a = torch.tensor([1 ,2,3])
b = torch.tensor([4 ,5 , 6])

a*b 


tensor([ 4, 10, 18])

In [30]:
#Addition : Think of 1 as [1 ,1, 1]
torch.tensor([1 ,2, 3]) + 1

tensor([2, 3, 4])

In [31]:
import torch 
X = torch.arange(6).view(2,3)
X

tensor([[0, 1, 2],
        [3, 4, 5]])

In [39]:
w = torch.tensor([1 ,2,3])

#Xw : Matrix multiplication 
X.matmul(w)


tensor([ 8, 26])

In [40]:
w = w.view(-1,1)  #same as reshape : column vector 
w

tensor([[1],
        [2],
        [3]])

In [42]:
X.matmul(w)   #function sees that matrix multiplication makes sense after taking transpose of w 

tensor([[ 8],
        [26]])

### Broadcasting 

In [43]:
torch.tensor([1 , 2, 3]) + 1


tensor([2, 3, 4])

In [46]:
t = torch.tensor([[1 ,2 , 3 ] , [4 , 5, 6]])
t ## works exactly like numpy

tensor([[1, 2, 3],
        [4, 5, 6]])

In [47]:
t + torch.tensor([ 1, 2, 3])

tensor([[2, 4, 6],
        [5, 7, 9]])