In [3]:
## Fully connected layer : linear layer 
import torch 
X = torch.arange(50 , dtype = torch.float).view(10,5) # make a 10 x 5 matrix of floats from 0 to 50
X

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.]])

In [4]:
#Make fully connected layer : attaributes weights and bias attached 
fc_layer = torch.nn.Linear(in_features = 5, out_features = 3) # (3 x 5)

In [6]:
fc_layer.weight #(3 x 5) out_features x in_features 

Parameter containing:
tensor([[ 0.4239, -0.4174, -0.0761,  0.0509,  0.0153],
        [-0.0590, -0.1249, -0.2650, -0.4047,  0.2078],
        [ 0.2174, -0.3346,  0.1236,  0.3338,  0.3465]], requires_grad=True)

In [7]:
fc_layer.bias #(1 x 3) #no of output features 

Parameter containing:
tensor([-0.0928,  0.2031,  0.0234], requires_grad=True)

In [9]:
##Printing things together 
print('X dim: ' , X.size())
print('W dim: ' , fc_layer.weight.size())
print('b dim: ' , fc_layer.bias.size())
#.size() is equivalent to shape 
A = fc_layer(X)
print('A: ' , A)
print('A dim: ' , A.size()) #no of training examples X no of outputs 

X dim:  torch.Size([10, 5])
W dim:  torch.Size([3, 5])
b dim:  torch.Size([3])
A:  tensor([[ -0.4484,  -0.8348,   2.3232],
        [ -0.4653,  -4.0641,   5.7564],
        [ -0.4822,  -7.2934,   9.1896],
        [ -0.4990, -10.5227,  12.6227],
        [ -0.5159, -13.7521,  16.0559],
        [ -0.5327, -16.9814,  19.4891],
        [ -0.5496, -20.2107,  22.9222],
        [ -0.5664, -23.4401,  26.3554],
        [ -0.5833, -26.6694,  29.7886],
        [ -0.6001, -29.8987,  33.2217]], grad_fn=<AddmmBackward0>)
A dim:  torch.Size([10, 3])
