### Autograd Example

In [2]:
##Imports 
import torch 
from torch.autograd import grad 
import torch.nn.functional as F 

In [3]:
##With reference to the computational graph, understand the following auto gradience example 
x = torch.tensor([3.])
w = torch.tensor([2.] , requires_grad = True) # needs to calculate gradient wrt 
b = torch.tensor([1.] , requires_grad = True) # needs to calculate gradient wrt 
a = F.relu(x*w + b)



In [4]:
a , b, w, x

(tensor([7.], grad_fn=<ReluBackward0>),
 tensor([1.], requires_grad=True),
 tensor([2.], requires_grad=True),
 tensor([3.]))

In [5]:
#syntax : grad(gradient_of , gradient_wrt , retain_graph = True)
grad(a , w , retain_graph = True)#retain_graph : retain the computation graph , by default : false 



tensor([3.])

In [9]:
grad(a,b)   #graph retained, and derivative calculated 

(tensor([1.]),)

In [12]:
##Implementing  my own ReLU 
x = torch.tensor([3.])
w = torch.tensor([2.] , requires_grad = True)
b = torch.tensor([1.] , requires_grad = True)

def my_relu(z): 
    if z>0 : 
        return z 
    else: 
        z[:] = 0 
        return z

a = my_relu(x*w + b)
grad(a,w)

(tensor([3.]),)

In [14]:
#Note that even though the derivative of ReLU is not defined at 0, PyTorch autograd will do something that is reasonable
#for practical purposes:

x = torch.tensor([-1.])
w = torch.tensor([1.] , requires_grad = True)
b = torch.tensor([1.] , requires_grad = True)
a = F.relu(x*w + b)
grad(a , w, retain_graph = True)

(tensor([-0.]),)